name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/llm-service
      - feature/server
      - test/llm-service
      - feature/llama_cpp
  pull_request:
    branches:
      - main
jobs:
  test_core_service:
    name: Run core-service Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        working-directory: server
        run: go mod download
      - name: Run gofmt
        run: |
          if [ "$(gofmt -s -l backend/ | wc -l)" -gt 0 ]; then
            echo "Code is not formatted. Run 'gofmt -s -w server/'"
            gofmt -s -l server/
            exit 1
          fi
      - name: Run tests
        working-directory: server
        run: go test -v -short ./...
      - name: Check test coverage
        working-directory: server
        run: |
          go test -coverprofile=coverage.out -short ./...
          go tool cover -func=coverage.out
  test_llm_service:
    name: Run LLM-service Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        working-directory: llm-service
        run: |
          pip install -r requirements.txt
          pip install pytest flake8
      - name: Run flake8 linting
        working-directory: llm-service
        run: flake8 .
      - name: Run pytest
        working-directory: llm-service
        run: pytest
  test_qdrant:
    name: Run tests and linting for Qdrant
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        working-directory: Qdrant/indexer
        run: |
          pip install -r requirements.txt
          pip install pytest flake8
      - name: Run flake8 linting
        working-directory: Qdrant/indexer
        run: flake8 .
  #      - name: Run pytest
  #        working-directory: Qdrant/indexer
  #        run: pytest -v
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          mkdir db_data
          docker compose -f docker/docker-compose.yml build llm_server core_server